import argparse
import treeswift


def relabel_multrees_simphy(ifil, ofil):
    """
    Relabels leaves of locus or gene trees generated by SimPhy; specifically,
    [sid]_[lid]_[gid] is relabled to [sid]. Also, removes internal node labels
    and branch lengths.

    Parameters
    ----------
    ifil : string
           name of input file (one newick string per line)
    ofil : string
           name of output file (one newick string per line)
    """
    with open(ifil, 'r') as fi, open(ofil, 'w') as fo:
       for line in fi.readlines():
            temp = "".join(line.split())
            tree = treeswift.read_tree(temp, "newick")

            for node in tree.traverse_postorder():
                if node.is_leaf():
                    node.label = node.label.split('_')[0]
                else:
                    node.label = None
                node.edge_length = None

            fo.write(tree.newick())
            fo.write('\n')


def main(args):
    base = args.input.rsplit('.', 1)
    prefix = base[0]
    suffix = base[1]
    output = base[0] + "-mult." + base[1]
    relabel_multrees_simphy(args.input, output)


if __name__=='__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument("-i", "--input", type=str,
                        help="Input file", required=True)

    main(parser.parse_args())
